<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Goods" Member="Good">
    <Type Name="Good">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="title" Member="Title" Storage="_title" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="description" Member="Description" Storage="_description" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="price" Member="Price" Storage="_price" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="image" Member="Image" Storage="_image" Type="System.Data.Linq.Binary" DbType="Binary(50)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>